CC = /usr/bin/gcc

TARGET = svm
CFLAGS = -c -g -DDEBUG
LINK	= -lm
MEMORY = ../memory/memory.o ../memory/storage.o

OBJS = svm.o opinfo.o native.o

all: $(TARGET)

$(TARGET): $(OBJS) $(MEMORY)
	make -C ../memory
	$(CC) -o $@ $^ $(LINK)

.c.o:
	$(CC) $(CFLAGS) $*.c

clean:
	rm -rf $(TARGET) *.o *~ disasm svm

